### ISSUE TITLE
Fails to compile on GHC 9.0.2

### ISSUE THREAD

**Issue by JosiahWI** [mstksg/uncertain#5]
The command issued was `stack install uncertain`.

```
uncertain           > configure
uncertain           > Configuring uncertain-0.3.1.0...
uncertain           > build
uncertain           > Preprocessing library for uncertain-0.3.1.0..
uncertain           > Building library for uncertain-0.3.1.0..
uncertain           > [1 of 6] Compiling Data.Hople
uncertain           > [2 of 6] Compiling Numeric.Uncertain
uncertain           > [3 of 6] Compiling Numeric.Uncertain.Correlated.Internal
uncertain           >    
uncertain           > /tmp/stack-2d776474f014098e/uncertain-0.3.1.0/src/Numeric/Uncertain/Correlated/Internal.hs:187:40: error:
uncertain           >     • Couldn't match type: forall t1.
uncertain           >                            M.IntMap (AD t1 (Sparse a1)) -> AD t1 (Sparse a1)
uncertain           >                      with: M.IntMap (AD t (Sparse a1)) -> AD t (Sparse a1)
uncertain           >       Expected: CVar s1 a1
uncertain           >                 -> M.IntMap (AD t (Sparse a1)) -> AD t (Sparse a1)
uncertain           >         Actual: CVar s1 a1
uncertain           >                 -> forall t. M.IntMap (AD t (Sparse a1)) -> AD t (Sparse a1)
uncertain           >     • In the first argument of ‘flip’, namely ‘cVarToF’
uncertain           >       In the first argument of ‘(<$>)’, namely ‘flip cVarToF us’
uncertain           >       In the first argument of ‘f’, namely ‘(flip cVarToF us <$> cs)’
uncertain           >     • Relevant bindings include
uncertain           >         us :: M.IntMap (AD t (Sparse a1))
uncertain           >           (bound at src/Numeric/Uncertain/Correlated/Internal.hs:187:27)
uncertain           >         cs :: f (CVar s1 a1)
uncertain           >           (bound at src/Numeric/Uncertain/Correlated/Internal.hs:187:23)
uncertain           >         f :: forall t. f (AD t (Sparse a1)) -> AD t (Sparse a1)
uncertain           >           (bound at src/Numeric/Uncertain/Correlated/Internal.hs:187:21)
uncertain           >         cVarToF :: CVar s1 a1
uncertain           >                    -> forall t. M.IntMap (AD t (Sparse a1)) -> AD t (Sparse a1)
uncertain           >           (bound at src/Numeric/Uncertain/Correlated/Internal.hs:185:9)
uncertain           >         cv :: CVar s1 a1
uncertain           >           (bound at src/Numeric/Uncertain/Correlated/Internal.hs:180:13)
uncertain           >         getCVar :: CVar s1 a1 -> M.IntMap (Uncert a1) -> Uncert a1
uncertain           >           (bound at src/Numeric/Uncertain/Correlated/Internal.hs:180:5)
uncertain           >     |
uncertain           > 187 |         cVarToF (CF f cs) us = f (flip cVarToF us <$> cs)
uncertain           >     |                                        ^^^^^^^

```

**Comment by mstksg** [comment]
ripperoni :( will look into this

**Comment by alaendle** [comment]
Still a problem to compile latest release with current stackage nightly set:
```
/home/andreas/stackage/stackage/tmp.xfaM/uncertain-0.4.0.0/src/Numeric/Uncertain.hs:249:22: error: [GHC-88464]
    Variable not in scope:
      foldl' :: (H3 a0 -> a0 -> H3 a0) -> H3 a1 -> c
    Suggested fixes:     
      • Perhaps use one of these:
          ‘foldl’ (imported from Prelude.Compat),
          ‘foldl1’ (imported from Prelude.Compat),
          ‘foldr’ (imported from Prelude.Compat)
      • Add ‘foldl'’ to the import list in the import of ‘Data.Foldable’
        (at src/Numeric/Uncertain.hs:60:1-29).
    |                    
249 |     foldStats = flip foldl' (H3 0 0 0) $
    |
```

**Comment by mstksg** [comment]
Thanks, @alaendle , hope it should be working now on 0.4.0.1, just confirmed! For some reason it was building for me on 9.8.2, i'm really confused now.
